### ISSUE TITLE
Zero in Bargraphs

### ISSUE THREAD

**Issue by Zmlina** [RonnyWeiss/APEX-Percent-Bargraphs#1]
Hi Ronny
  Do you notice that if there is one of value is zero,in the bargraphs, bar displays previous value?

Thx

EXAMPLE:

SELECT
    DECODE( ROWNUM, 1, 'ORACLE APEX', 2, 'HTML5', 3, 'CSS3', 4, 'JavaScript', NULL ) AS TITLE,
    --ROUND( DBMS_RANDOM.VALUE( 30, 100 ) ) AS VALUE,
    DECODE( ROWNUM, 1, 37, 2, 0, 3, 25, 4, 0, NULL ) AS VALUE,
    DECODE( ROWNUM, 1, '#0572CE', 2, 'rgb(233,98,41)', 3, 'rgb(38,143,201)', 4, 'rgb(239,216,29)', NULL ) AS TITLE_COLOR,
    NULL AS BAR_COLOR
FROM
    DUAL
CONNECT BY ROWNUM <= 4

**Comment by RonnyWeiss** [comment]
Hello thank you for the issues. In version 1.1 it's fixed. Have fun with the plug-in :-)
