### ISSUE TITLE
Unable to install plugin

### ISSUE THREAD

**Issue by darkojic** [RonnyWeiss/APEX-Percent-Bargraphs#2]
Hello,
I am trying to import this plugin into my workspace but it results with error:

> Execution of the statement was unsuccessful. ORA-20001: Error creating plug-in attribute id="54984355943328680426"	ORA-02290: check constraint (APEX_050100.PLUGIN_STD_ATTR_NAME_CK) violated

I am using workspace with Application Express 5.1.4.00.08 version installed.

**Comment by RonnyWeiss** [comment]
which file did you install? did you download the release zip file and installed the plugin included there?

**Comment by RonnyWeiss** [comment]
For weeks I've had no response so I would close the issue. If the problem persists, please reopen.
