### ISSUE TITLE
Error on installing

### ISSUE THREAD

**Issue by darkojic** [RonnyWeiss/APEX-Percent-Bargraphs#3]
Hello,
I am trying to import this plugin into my workspace but it results with error:

`
Execution of the statement was unsuccessful. ORA-20001: Error creating plug-in attribute id="55012359957190328044"	ORA-02290: check constraint (APEX_050100.PLUGIN_STD_ATTR_NAME_CK) violated
begin
wwv_flow_api.create_plugin(
 p_id=>wwv_flow_api.id(54884691442646934817)
,p_plugin_type=>'REGION TYPE'
,p_name=>'APEX.PERECENT.BARGRAPHS'
,p_display_name=>'APEX Percent Bargraphs'
,p_supported_ui_types=>'DESKTOP:JQM_SMARTPHONE'
,p_plsql_code=>wwv_flow_string.join(wwv_flow_t_varchar2(
'FUNCTION F_AJAX (',
'    P_REGION   IN         APEX_PLUGIN.T_REGION,',
'    P_PLUGIN   IN         APEX_PLUGIN.T_PLUGIN',
') RETURN APEX_PLUGIN.T_REGION_AJAX_RESULT IS',
'    VR_RESULT   APEX_PLUGIN.T_REGION_AJAX_RESULT;',
'BEGIN',
'    APEX_UTIL.JSON_FROM_SQL(SQLQ   => RTRIM(',
'        P_REGION.SOURCE,',
'        '';''',
'    ));',
'    RETURN VR_RESULT;',
'END;',
'',
'FUNCTION F_RENDER (',
'    P_REGION                IN                      APEX_PLUGIN.T_REGION,',
'    P_PLUGIN                IN                      APEX_PLUGIN.T_PLUGIN,',
'    P_IS_PRINTER_FRIENDLY   IN                      BOOLEAN',
') RETURN APEX_PLUGIN.T_REGION_RENDER_RESULT IS',
'',
'    VR_RESULT         APEX_PLUGIN.T_REGION_RENDER_RESULT;',
'    VR_ITEMS2SUBMIT   APEX_APPLICATION_PAGE_REGIONS.AJAX_ITEMS_TO_SUBMIT%TYPE := APEX_PLUGIN_UTIL.PAGE_ITEM_NAMES_TO_JQUERY(P_REGION.AJAX_ITEMS_TO_SUBMIT);',
'BEGIN',
'    APEX_CSS.ADD_FILE(',
'        P_NAME        => ''style.min'',',
'        P_DIRECTORY   => P_PLUGIN.FILE_PREFIX,',
'        P_VERSION     => NULL,',
'        P_KEY         => ''pergrcsssrc''',
'    );',
'',
'    APEX_JAVASCRIPT.ADD_LIBRARY(',
'        P_NAME        => ''script.min'',',
'        P_DIRECTORY   => P_PLUGIN.FILE_PREFIX,',
'        P_VERSION     => NULL,',
'        P_KEY         => ''pergrjssrc''',
'    );',
'',
'    HTP.P(''<div id="'' || APEX_ESCAPE.HTML_ATTRIBUTE( P_REGION.STATIC_ID ) || ''-p"></div>'');',
'',
'    APEX_JAVASCRIPT.ADD_ONLOAD_CODE( ''apexSkillBar.render(''',
'     || APEX_JAVASCRIPT.ADD_VALUE( P_REGION.STATIC_ID, TRUE )    ',
'     || APEX_JAVASCRIPT.ADD_VALUE( APEX_PLUGIN.GET_AJAX_IDENTIFIER, TRUE )',
'     || APEX_JAVASCRIPT.ADD_VALUE( P_REGION.NO_DATA_FOUND_MESSAGE, TRUE )',
'     || APEX_JAVASCRIPT.ADD_VALUE( VR_ITEMS2SUBMIT, TRUE )',
'     || APEX_JAVASCRIPT.ADD_VALUE( P_REGION.ESCAPE_OUTPUT, TRUE )',
'     || APEX_JAVASCRIPT.ADD_VALUE( P_REGION.ATTRIBUTE_01, FALSE )',
'     || '');'' );',
'',
'    RETURN VR_RESULT;',
'END;'))
,p_api_version=>1
,p_render_function=>'F_RENDER'
,p_ajax_function=>'F_AJAX'
,p_standard_attributes=>'SOURCE_LOCATION:AJAX_ITEMS_TO_SUBMIT:NO_DATA_FOUND_MESSAGE:ESCAPE_OUTPUT'
,p_substitute_attributes=>true
,p_subscribe_plugin_settings=>true
,p_help_text=>'This plug-in is used to visualize percent bargraphs in APEX.'
,p_version_identifier=>'1.0.2'
,p_about_url=>'https://github.com/RonnyWeiss/APEX-Percent-Bargraphs'
,p_files_version=>1419
);
wwv_flow_api.create_plugin_attribute(
 p_id=>wwv_flow_api.id(54905435947487748190)
,p_plugin_id=>wwv_flow_api.id(54884691442646934817)
,p_attribute_scope=>'COMPONENT'
,p_attribute_sequence=>1
,p_display_sequence=>10
,p_prompt=>'Refresh Time (Seconds)'
,p_attribute_type=>'INTEGER'
,p_is
Contact your administrator. Details about this incident are available via debug id "718357".`

I am using workspace with Application Express 5.1.4.00.08 version installed.

I have downloaded ZIP file from here, and tried to import plugin, but this error has occured.

1. I log into workspace.
2. Go to my application
3. Choose shared components
4. Choose plug-ins
5. Click on import

I have previously opened the same issue, but it have been closed yesterday, before I wrote the answer.

**Comment by darkojic** [comment]
Hi, I think that issue could have something with version of APEX. If plug-in is developed  for 19.1 and I try it on 5.2, that's sure could be a reason.

If you can confirm, this can be closed.

Thanks.

**Comment by RonnyWeiss** [comment]
Yes u need APEX 5.1.3 or higher
